language: go

go:
  - 1.6

install:
  - mkdir $GOPATH/bin
  - export PATH=$PATH:$GOPATH/bin
  - curl -s -L https://github.com/Masterminds/glide/releases/download/0.9.3/glide-0.9.3-linux-amd64.tar.gz | tar zxv -C $GOPATH/bin --strip-components=1
  - glide install

script:
  - go test -v
